data: 
    extends: 
        file: common.yml
        service: data

nginx:
    extends: 
        file: common.yml
        service: nginx
    links:
        - php-fpm
    volumes_from:
        - data
    volumes:
        - /etc/nginx/nginx-conf/products/nginx.conf:/etc/nginx/nginx.conf:ro

php-fpm:
    extends: 
        file: common.yml
        service: php-fpm
    volumes_from:
        - data


